name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    name: Deploy To Heroku
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch the DB Credentials
        run: |
          touch 'appsettings.json'
          echo '${{ secrets.APP_SETTINGS_JSON }}' > 'appsettings.json'
          touch 'appsettings.Development.json'
          echo '${{ secrets.APP_SETTINGS_DEV_JSON }}' > 'appsettings.Development.json'

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Build App
        run: dotnet build -c Release

      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API }}
          heroku_app_name: "include-type"
          heroku_email: "${{ secrets.HEROKU_USERNAME }}"
          usedocker: true